version: '3.9'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      - MB_DB_TYPE=mysql
      - MB_DB_DBNAME=${MB_DB_DBNAME}
      - MB_DB_PORT=${MB_DB_PORT}
      - MB_DB_USER=${MB_DB_USER}
      - MB_DB_PASS=${MB_DB_PASS}
      - MB_DB_HOST=mysql
      - MB_JETTY_HOST=0.0.0.0
    networks:
      - metanet
    depends_on:
      - mysql

  mysql:
    image: mariadb:latest
    container_name: mysql_metabase
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MB_DB_PASS}
      - MYSQL_DATABASE=${MB_DB_DBNAME}
      - MYSQL_USER=${MB_DB_USER}
      - MYSQL_PASSWORD=${MB_DB_PASS}
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    networks:
      - metanet

  nginx:
    image: nginx:latest
    container_name: nginx_metabase
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - metanet
    depends_on:
      - metabase

networks:
  metanet:
    driver: bridge
